security:
    # Configuration du hachage des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Configuration des fournisseurs d'utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Admin
                property: email

    # Configuration des pare-feu
    firewalls:
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AdminFormAuthentificatorAuthenticator

            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_home

            logout:
                path: app_logout

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

            # Définition de l'authentificateur d'entrée
            entry_point: App\Security\AdminFormAuthentificatorAuthenticator

    # Contrôle d'accès pour les différentes parties du site
    access_control:
       - { path: ^/admin, roles: ROLE_ADMIN }
       - { path: ^/profile, roles: ROLE_USER }

# Configuration spécifique aux tests
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
